start: expression*

expression: single_quote_expression
    | double_quote_expression
    | substitution
    | STRING
    | INTERNAL_STRING

single_quote_expression: SQ NO_SQ? SQ

double_quote_expression: DQ double_quote_internal_expression* DQ

double_quote_internal_expression: substitution
    | INTERNAL_STRING

STRING: /[^"'$]+/
INTERNAL_STRING: /[^"$]+/

substitution: DOLLAR NAME
DOLLAR: "$"
SQ: "'"
NO_SQ: /[^']+/
DQ: "\""
NAME: /[a-zA-Z][a-zA-Z0-9]*/
